### ISSUE TITLE
How to export?

### ISSUE THREAD

**Issue by s4m-mo** [RythenGlyth/manim-pptx#1]
Been looking for something like this for a while. But how do you export to a `.pptx` file?

**Comment by RythenGlyth** [comment]
The pptx will be generated automatically each time you run manim if you use PPTXScene as your base class.
You can look at the example code in the README.md. If you run this code through manim, it should generate the pptx

**Comment by s4m-mo** [comment]
Thanks. I've been looking for this for _months_ for various projects of mine. Thank you so much.
